version: "3"
services:
  app:
    image: takuyayone/fastapi-sample:1.0.0
    platform: linux/amd64
    build: .
    ports:
      - "8000:8000"
    container_name: app
    tty: true
    volumes:
      - ./app:/usr/src/app